<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>elastiqp</name>
  <version>0.1.0</version>
  <description>ElastiQP: An elastic QP solver for robot control</description>
  <maintainer email="danielpmorton@gmail.com">Daniel Morton</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>cmake</buildtool_depend>
  <depend>eigen</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>